### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by Umoren** [Seokky/vue-pincode-input#19] opened 2020-10-12 20:51 UTC
-  I'm trying to apply styles in a component. I am using nuxt
`<template>
  <div>

    <div class="text-center settings-heading">
      <img src="/dashboard/tPin.svg" height="100" width="100" alt="Trasaction Pin screen">
    </div>

    <div class="input-wrapper my-5 d-flex flex-column align-items-center " v-if="enterOldPin">

      <div class="text-center" >
        <h4 class="text-bold">Enter your old PIN </h4>
        <p class="text-muted"> An easier way to make payments</p>
      </div>
        <PincodeInput
          v-model="oldCode"
          placeholder=""
          :secure = oldCode
        />

    <button class="btn btn-primary my-5" @click="changePinScreen()" :disabled="oldCode.length !== 4"> Continue </button>
    </div>

    <div v-if="createNewPin">

      <div class="input-wrapper my-5 d-flex flex-column align-items-center ">

        <div class="text-center">
          <h4 class="text-bold">Create your PIN </h4>
          <p class="text-muted"> Enjoy an easier way to make payments</p>
        </div>
          <PincodeInput
            v-model="newCode"
            placeholder=""
            :secure = oldCode
            class=""
          />
          <button class="btn btn-primary my-5" @click="gotoConfirmPin()" > Continue </button>
      </div>

      <div v-if="showConfirmPin" class="input-wrapper my-5 d-flex flex-column align-items-center ">
        <div class= "text-center">
          <h4 class="text-bold">Confirm your PIN </h4>
          <p class="text-muted"> Enjoy an easier way to make payments</p>
        </div>
        <PincodeInput
          v-model="confirmCode"
          placeholder=""
          :secure = oldCode
        />

       <button class="btn btn-primary my-5" @click="changeTransactionPin" :disabled="disabled"> Continue </button>
      </div>
    </div>

  </div>
</template>

<script>
import PincodeInput from 'vue-pincode-input'
export default {
  components: {
    PincodeInput
  },
}

<style scoped>

.head-primary {
  color: var(--theme-color);
}

p {
  color: var(--font-color);
}

.user-details-card {
  padding: 1rem;
}

input.vue-pincode-input {
  background: #ffffff;
  height: 56px;
  max-width: 70px;
  margin-left: 1rem;
  font-size: 2.5rem;
}

</style>
`

- I also get 'Cannot import statement outside module' whenever i refresh the page in nuxt projext

**Comment by Seokky** [comment] 2020-11-02 22:19
It doesn't really look like the plugin is the cause of the problem. 

`:secure = oldCode` line is invalid at least. 

Also you need to use `deep` modificator to access plugin's styles inside the scoped styles. Although, to be honest, I'm not sure if this is necessary when working with pure css...

And one more thing: your code doesn't have the closing tag `</script>`.

**Closed by Seokky** 2020-11-02 22:19 UTC
